#! /bin/bash

rm -f *.{blg,bbl,toc,out,log,aux,dvi,maf,mtc,nlo,brf}*

./compile-a

rm -f AnalysisNote.pdf
pdflatex AnalysisNote
bibtex AnalysisNote
pdflatex AnalysisNote
pdflatex AnalysisNote

rm -f *.{blg,bbl,toc,out,log,aux,dvi,maf,mtc,nlo,brf}*
