#! /bin/bash

rm -f *.{blg,bbl,toc,out,log,aux,dvi,maf,mtc,nlo,brf}*

rm -f 1-Answers-Review.pdf
pdflatex 1-Answers-Review
pdflatex 1-Answers-Review

rm -f *.{blg,bbl,toc,out,log,aux,dvi,maf,mtc,nlo,brf}*
